### ISSUE TITLE
Global Evolution Checks

### ISSUE THREAD

**Issue by devip** [devip/SFPD-.NET#18]
Analyse ==> [lien ici](https://gcloudbelgium-my.sharepoint.com/:w:/r/personal/paul-henri_deville_sfpd_fgov_be/Documents/Documents/HRNET/SFPD.Wf.CheckDispenser%20-%20Analyse.docx?d=w8d2bdedf2f1d404e80d00b79671e9ac5&csf=1&e=jcoygX)
- [x] Voir comment a été fait le fichier pour medex. #13 
- [x] Filtrer les personnes pensionnées #53  
- [x] Ajouter l'entité pour faire une ligne de csv #45
- [x] Implémenter la création du fichier dans le job #47
- [x] Modifier la config pour #46  ( et aussi voir #39) _>>> J'attend rep. de Seb_
- [x] Vérifier l'interaction du read only dans la connStr. #43 
- [x] Ajouter la classe pour entity frameword et s'assurer que ce ne sont que des read #44
- [x] Ajouter un Job  (+ Traduction) #40
- [x] Demande à Danny Herpol #14 
- [x] Jira CR #16 
- [x] Récupérer la branche CR pour faire évoluer le développement. #15 
- [x] Modifier le(s) fichiers appsettings #17 

@devip
