### ISSUE TITLE
Tâches globales Tests HRNET

### ISSUE THREAD

**Issue by devip** [devip/SFPD-.NET#23]
- [ ] Récupérer mail de seb et faire sous Tâches #21
- [ ] Test HRNET : birth #30
- [ ] Test HRNET : blood-collect #28
- [ ] Test HRNET : dynamo #27
- [ ] Test HRNET : internet-intervention #Test HRNET : internet-intervention
- [ ] Test HRNET : note-sixty #25
- [ ] Test HRNET : nursery (User page) #24
- [ ] Test HRNET : nursery (Management page) #29
- [ ] Test HRNET : strike #31
